version: '3.7'

services:
  worldbank-backend-producer:
    build:
      context: ./backend-worldbank-producer/
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: backend-producer
    restart: always
    networks:
      - bank_networking
    ports:
      - '8080:8080'
    expose:
      - '8080'
      - '6831'
      - '9090'
      - '9200'
      - '9300'
      - '9600'
      - '5000'
      - '12201'
      - '16686'
      - '8180'
      - '8280'
      - '8380'
      - '3000'

  worldbank-backend-consumer:
    build:
      context: ./backend-wordlbank-consumer/
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: backend-consumer
    restart: always
    networks:
      - bank_networking
    ports:
      - '8081:8080'
    expose:
      - '8080'
      - '6831'
      - '9090'
      - '9200'
      - '9300'
      - '9600'
      - '5000'
      - '12201'
      - '16686'
      - '8180'
      - '8280'
      - '8380'
      - '3000'

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: bank-tracing
    restart: always
    networks:
      - bank_networking
    volumes:
      - 'bank_tracing_data:/data/jaeger'
    ports:
      - '6831:6831/udp'
      - '8180:16686'
    expose:
      - '6831'
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M

  prometheus:
    image: prom/prometheus:latest
    container_name: bank-prometheus
    restart: always
    networks:
      - bank_networking
    volumes:
      - 'bank_prometheus_data:/data/prometheus'
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    ports:
      - '8280:9090'
    expose:
      - '9090'
      - '8080'
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
    container_name: bank-elasticsearch
    restart: always
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    networks:
      - bank_networking
    deploy:
      resources:
        limits:
          memory: 710M
        reservations:
          memory: 300M

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.8.2
    container_name: bank-logstash
    restart: always
    volumes:
      - source: ./pipelines
        target: /usr/share/logstash/pipeline
        type: bind
    ports:
      - '12201:12201/udp'
      - '5000:5000'
      - '9600:9600'
    networks:
      - bank_networking
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          memory: 100M

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.8.2
    container_name: bank-kibana
    restart: always
    ports:
      - '8380:5601'
    networks:
      - bank_networking
    depends_on:
      - elasticsearch
      - logstash
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M

  grafana:
    image: 'grafana/grafana'
    container_name: bank-grafana
    restart: always
    networks:
      - bank_networking
    ports:
      - '8480:3000'
    expose:
      - '3000'
    depends_on:
      - kibana
    volumes:
      - 'bank_grafana_data:/data/grafana'
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M

volumes:
  bank_tracing_data:
    driver: local
  bank_prometheus_data:
    driver: local
  bank_grafana_data:
    driver: local

networks:
  bank_networking:
    driver: bridge
